apiVersion: v2
description: SQL Server 2019 Linux Helm Chart
name: mssql
version: 0.1.0
appVersion: "15.0.4153.1"
type: application
home: https://hub.docker.com/_/microsoft-mssql-server
icon: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1I4Dx
sources:
- https://hub.docker.com/_/microsoft-mssql-server
